from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable


@runtime_checkable
class PropertiesCatalog(Protocol):
    def physical_keys(self) -> list[str]: ...
    def mechanical_keys(self) -> list[str]: ...
    def get_meta(self, key: str) -> dict: ...
    def supports_temperature(self, key: str) -> bool: ...
    def all_keys(self) -> list[str]: ...
    def is_physical(self, key: str) -> bool: ...
    def is_mechanical(self, key: str) -> bool: ...


@runtime_checkable
class UnitConverter(Protocol):
    def convert(self, value: float, from_unit: str, to_unit: str) -> float: ...
    def units_for_type(self, unit_type: str) -> list[str]: ...
    def system_unit(self) -> str: ...
    def display_label(self, key: str) -> str: ...


@runtime_checkable
class HardnessTable(Protocol):
    SYSTEM_UNIT: str

    def convert(self, value: float, from_unit: str, to_unit: str) -> float | None: ...
    def column_names(self) -> list[str]: ...
    def is_supported_unit(self, unit: str) -> bool: ...


@runtime_checkable
class MaterialRepository(Protocol):
    work_dir: str
    materials: list
    application_areas: list[str]
    current_material: object | None
    source_manager: "SourceService"

    def load_materials_from_dir(self, directory: str | Path) -> None: ...
    def load_application_areas(self) -> None: ...
    def get_by_id(self, material_id: str): ...
    def list_summary(self) -> list[dict]: ...
    def save_material(self, material) -> None: ...


@runtime_checkable
class SourceService(Protocol):
    def load(self) -> None: ...
    def save(self) -> None: ...
    def get_all(self, group: str | None = None) -> list[dict]: ...
    def get_source_by_id(self, source_id: str) -> dict | None: ...
    def get_name_by_id(self, source_id: str) -> str: ...
    def add_source(
        self, name: str, description: str = "", hyperlink: str = "", group: str | None = None
    ) -> str: ...
    def update_source(
        self, source_id: str, name: str, description: str, hyperlink: str
    ) -> bool: ...
    def delete_source(self, source_id: str) -> None: ...
    def list_all(self) -> list[dict]: ...
    def get_by_id(self, source_id: str) -> dict | None: ...

    @staticmethod
    def short_label(source: dict) -> str: ...


@runtime_checkable
class StorageBackend(Protocol):
    @property
    def directory(self) -> Path: ...

    def list_material_paths(self) -> list[Path]: ...
    def read_json(self, path: Path) -> dict: ...
    def write_json(self, path: Path, data: dict) -> None: ...
    def exists(self, path: Path) -> bool: ...
