from typing import Protocol

class PropertiesCatalog(Protocol):
    def physical_keys(self) -> list[str]:
        ...
    def mechanical_keys(self) -> list[str]:
        ...
    def get_meta(self, key:str) -> dict:
        ...
    def supports_temperature(self, key:str) -> bool:
        ...

class UnitConverter(Protocol):
    def convert(self, value:float, from_unit:str, to_unit:str) -> float:
        ...
    def units_for_type(self, unit_type:str) -> list[str]:
        ...
    def system_unit(self) -> str:
        ...
    def display_label(self, key:str) -> str:
        ...

class MaterialRepository(Protocol):
    def load_all(self) -> dict:
        ...
    def save(self, data:dict) -> None:
        ...
    def application_areas(self) -> list[str]:
        ...
    
class SourceService(Protocol):
    def list_all(self) -> list[dict]:
        ...
    def get_by_id(self, id:str) -> dict:
        ...
    def short_label(self, source:dict) -> str:
        ...
    