name: Validate branch flow

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only dev branch can merge into main"
            exit 1
          fi
